MIN_MARKET_VOLUME_USD = 10_000
MIN_ACTIVE_MINUTES = 1_000
MIN_OVERLAP_MINUTES = 1_000

EQUIVALENCE_MEAN_ABS_DIFF_MAX = 0.02
EQUIVALENCE_CURRENT_ABS_DIFF_MAX = 0.03

IMPLICATION_EPSILON = 0.01
IMPLICATION_VIOLATION_MEAN_MAX = 0.005
IMPLICATION_CURRENT_SLACK = 0.02

EXCLUSION_EPSILON = 0.01
EXCLUSION_VIOLATION_MEAN_MAX = 0.005
EXCLUSION_CURRENT_SUM_MAX = 1.02

COMPLEMENT_LOW_OVERLAP_MINUTES = 10
COMPLEMENT_CURRENT_GAP_VIOLATION_MIN = 0.02
COMPLEMENT_MEAN_GAP_VIOLATION_MIN = 0.01
